#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CRM")]
	public partial class siparistableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public siparistableDataContext() : 
				base(global::CRM.Properties.Settings.Default.CRMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public siparistableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public siparistableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public siparistableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public siparistableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<siparisEkleForm> siparisEkle
		{
			get
			{
				return this.GetTable<siparisEkleForm>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.siparisEkle")]
	public partial class siparisEkleForm
	{
		
		private int _id;
		
		private string _siparisVeren;
		
		private string _siparisUrun;
		
		private int _siparisMiktari;
		
		private string _tarih;
		
		
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisVeren", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string siparisVeren
		{
			get
			{
				return this._siparisVeren;
			}
			set
			{
				if ((this._siparisVeren != value))
				{
					this._siparisVeren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisUrun", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string siparisUrun
		{
			get
			{
				return this._siparisUrun;
			}
			set
			{
				if ((this._siparisUrun != value))
				{
					this._siparisUrun = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisMiktari", DbType="Int NOT NULL")]
		public int siparisMiktari
		{
			get
			{
				return this._siparisMiktari;
			}
			set
			{
				if ((this._siparisMiktari != value))
				{
					this._siparisMiktari = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tarih
		{
			get
			{
				return this._tarih;
			}
			set
			{
				if ((this._tarih != value))
				{
					this._tarih = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
