#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CRM")]
	public partial class tekliftableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public tekliftableDataContext() : 
				base(global::CRM.Properties.Settings.Default.CRMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public tekliftableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tekliftableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tekliftableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tekliftableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<teklifEkle> teklifEkle
		{
			get
			{
				return this.GetTable<teklifEkle>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.teklifEkle")]
	public partial class teklifEkle
	{
		
		private int _id;
		
		private string _teklifVeren;
		
		private string _teklifVerilenSirket;
		
		private double _teklifDeger;
		
		private string _tarih;
		
		
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teklifVeren", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string teklifVeren
		{
			get
			{
				return this._teklifVeren;
			}
			set
			{
				if ((this._teklifVeren != value))
				{
					this._teklifVeren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teklifVerilenSirket", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string teklifVerilenSirket
		{
			get
			{
				return this._teklifVerilenSirket;
			}
			set
			{
				if ((this._teklifVerilenSirket != value))
				{
					this._teklifVerilenSirket = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teklifDeger", DbType="Float NOT NULL")]
		public double teklifDeger
		{
			get
			{
				return this._teklifDeger;
			}
			set
			{
				if ((this._teklifDeger != value))
				{
					this._teklifDeger = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tarih
		{
			get
			{
				return this._tarih;
			}
			set
			{
				if ((this._tarih != value))
				{
					this._tarih = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
