<?xml version="1.0" encoding="utf-8"?><Database Name="CRM" Class="tekliftableDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MERT\MSSQLSERVER01;Initial Catalog=CRM;Integrated Security=True" SettingsObjectName="CRM.Properties.Settings" SettingsPropertyName="CRMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.teklifEkle" Member="teklifEkle">
    <Type Name="teklifEkle">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="teklifVeren" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="teklifVerilenSirket" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="teklifDeger" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="tarih" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>